export const NETWORK_COMPANIES = [
  "Palo Alto",
  "Fortinet",
  "Cisco",
  "Check Point",
  "Sophos",
  "McAfee",
  "Trend Micro",
  "CrowdStrike",
  "Barracuda",
  "SonicWall",
  "Bitdefender",
  "FireEye",
  "Qualys",
  "WatchGuard",
  "Zscaler",
  "A10",
  "Radware",
  "Proofpoint",
  "CyberArk",
  "Elastic Security",
  "Ivanti",
  "Forcepoint",
  "F5",
  "Tanium",
  "SentinelOne",
  "AlienVault",
  "Rapid7",
  "Imperva",
  "LogRhythm",
  "Darktrace",
  "Vormetric",
  "Paessler",
];

export const NETWORK_CATEGORIES = [
  "Bộ định tuyến (Router)",
  "Bộ chuyển mạch (Switch)",
  "Điểm truy cập (Access Point)",
  "Card mạng (Network Interface Card)",
  "Modem",
  "Cáp mạng",
  "Thiết bị mở rộng sóng Wi-Fi (Wi-Fi Extender)",
  "Tường lửa (Firewall)",
  "Hệ thống quản lý mối đe dọa hợp nhất (UTM)",
  "Hệ thống phát hiện xâm nhập (IDS/IPS)",
  "Bộ cân bằng tải (Load Balancer)",
  "Thiết bị lưu trữ mạng (NAS)",
  "Bộ điều khiển mạng (Network Controller)",
  "Thiết bị VPN (VPN Concentrator)",
  "Máy chủ proxy (Proxy Server)",
  "Phần mềm giám sát (Monitoring Software)",
  "Phần mềm quản lý mạng (Network Management Software)",
  "Phần mềm bảo mật (Security Software)",
  "Bản quyền bảo mật (Security Subscription)",
  "Dịch vụ hỗ trợ kỹ thuật (Technical Support Service)",
  "Bản quyền phần mềm (Software License)",
  "Bộ chuyển đổi quang (Media Converter)",
  "Mô-đun thu phát (SFP Module)",
  "Anten Wi-Fi",
  "Phụ kiện mạng",
];

export const deviceToCategoryMap = {
  "PA-5220": "Tường lửa (Firewall)",
  "PA-3220": "Tường lửa (Firewall)",
  PRTG: "Phần mềm giám sát (Monitoring Software)",
  "Precision AI Network Security": "Bản quyền bảo mật (Security Subscription)",
  "Advanced Threat Prevention": "Bản quyền bảo mật (Security Subscription)",
  "Partner enabled premium support":
    "Dịch vụ hỗ trợ kỹ thuật (Technical Support Service)",
  FortiGate: "Tường lửa (Firewall)",
  "Cisco ASA": "Tường lửa (Firewall)",
  SolarWinds: "Phần mềm giám sát (Monitoring Software)",
  Nagios: "Phần mềm giám sát (Monitoring Software)",
  F5: "Bộ cân bằng tải (Load Balancer)",
};
