export const NETWORK_COMPANIES = [
  "Palo Alto",
  "Fortinet",
  "Cisco",
  "Check Point",
  "Sophos",
  "McAfee",
  "Trend Micro",
  "CrowdStrike",
  "Barracuda",
  "SonicWall",
  "Bitdefender",
  "FireEye",
  "Qualys",
  "WatchGuard",
  "Zscaler",
  "A10",
  "Radware",
  "Proofpoint",
  "CyberArk",
  "Elastic Security",
  "Ivanti",
  "Forcepoint",
  "F5",
  "Tanium",
  "SentinelOne",
  "AlienVault",
  "Rapid7",
  "Imperva",
  "LogRhythm",
  "Darktrace",
  "Vormetric",
  "Paessler",
];

export const NETWORK_CATEGORIES = [
  { name: "Thiết bị định tuyến (Router)" },
  { name: "Thiết bị chuyển mạch (Switch)" },
  { name: "Thiết bị bảo mật (Firewall)" },
  { name: "Thiết bị Wifi" },
  { name: "Cáp và dây nhảy" },
  { name: "Phụ kiện đấu nối mạng" },
  { name: "Thiết bị lưu trữ và máy chủ" },
  { name: "Thiết bị chuyển đổi quang-điện" },
  { name: "Tủ mạng và bộ lưu điện" },
  { name: "Phần mềm và dịch vụ quản lý mạng" },
  { name: "Khác" },
];

export const deviceToCategoryMap = {
  "PA-5220": "Tường lửa (Firewall)",
  "PA-3220": "Tường lửa (Firewall)",
  PRTG: "Phần mềm giám sát (Monitoring Software)",
  "Precision AI Network Security": "Bản quyền bảo mật (Security Subscription)",
  "Advanced Threat Prevention": "Bản quyền bảo mật (Security Subscription)",
  "Partner enabled premium support":
    "Dịch vụ hỗ trợ kỹ thuật (Technical Support Service)",
  FortiGate: "Tường lửa (Firewall)",
  "Cisco ASA": "Tường lửa (Firewall)",
  SolarWinds: "Phần mềm giám sát (Monitoring Software)",
  Nagios: "Phần mềm giám sát (Monitoring Software)",
  F5: "Bộ cân bằng tải (Load Balancer)",
};
